// <auto-generated />
using System;
using CompressionForce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompressionForce.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105064310_AddUserGroups")]
    partial class AddUserGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Compression_Force.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AwcForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcLower")
                        .HasColumnType("real");

                    b.Property<float?>("AwcUpper")
                        .HasColumnType("real");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("FillDepthS1")
                        .HasColumnType("real");

                    b.Property<float?>("FillDepthS2")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS1")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxTurretRpm")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<float?>("RejLower")
                        .HasColumnType("real");

                    b.Property<float?>("RejUpper")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS2")
                        .HasColumnType("real");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<float?>("TabletHardness")
                        .HasColumnType("real");

                    b.Property<float?>("TabletThickness")
                        .HasColumnType("real");

                    b.Property<string>("ToolType")
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.RecipeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AwcForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcLower")
                        .HasColumnType("real");

                    b.Property<float?>("AwcUpper")
                        .HasColumnType("real");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<float?>("FillDepthS1")
                        .HasColumnType("real");

                    b.Property<float?>("FillDepthS2")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS1")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxTurretRpm")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("RecipeAlteredBy")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<float?>("RejLower")
                        .HasColumnType("real");

                    b.Property<float?>("RejUpper")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS2")
                        .HasColumnType("real");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<float?>("TabletHardness")
                        .HasColumnType("real");

                    b.Property<float?>("TabletThickness")
                        .HasColumnType("real");

                    b.Property<string>("ToolType")
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("RecipeHistroys");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ERemail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERlevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERpassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserManagements");
                });
#pragma warning restore 612, 618
        }
    }
}
