// <auto-generated />
using System;
using CompressionForce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompressionForce.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Compression_Force.Domain.Entities.AlarmLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AlarmCreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlarmDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlarmLogs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Activity");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EventDescription");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BatchCondition")
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<string>("BatchQty")
                        .HasColumnType("text");

                    b.Property<string>("BatchSize")
                        .HasColumnType("text");

                    b.Property<string>("BatchStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoodQty")
                        .HasColumnType("text");

                    b.Property<string>("LeftQty")
                        .HasColumnType("text");

                    b.Property<string>("ProdusedQty")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("RejectionQty")
                        .HasColumnType("text");

                    b.Property<string>("S2GoodQty")
                        .HasColumnType("text");

                    b.Property<string>("S2RejectionQty")
                        .HasColumnType("text");

                    b.Property<string>("TabletQty")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.BatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .HasColumnType("text");

                    b.Property<long?>("BatchSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EReventType")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BatchHistories");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.CurrentBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwcLower")
                        .HasColumnType("text");

                    b.Property<string>("AwcUpper")
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejLower")
                        .HasColumnType("text");

                    b.Property<string>("RejUpper")
                        .HasColumnType("text");

                    b.Property<string>("S1AwcLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1AwcSetLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1AwcUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1FeederRatio")
                        .HasColumnType("text");

                    b.Property<string>("S1FillCam")
                        .HasColumnType("text");

                    b.Property<string>("S1FillDepth")
                        .HasColumnType("text");

                    b.Property<string>("S1MainPenetration")
                        .HasColumnType("text");

                    b.Property<string>("S1MainThickness")
                        .HasColumnType("text");

                    b.Property<string>("S1PrePenetration")
                        .HasColumnType("text");

                    b.Property<string>("S1PreThickness")
                        .HasColumnType("text");

                    b.Property<string>("S1RejLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1RejUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2AwcLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2AwcSetLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2AwcUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2FeederRatio")
                        .HasColumnType("text");

                    b.Property<string>("S2FillCam")
                        .HasColumnType("text");

                    b.Property<string>("S2FillDepth")
                        .HasColumnType("text");

                    b.Property<string>("S2MainPenetration")
                        .HasColumnType("text");

                    b.Property<string>("S2MainThickness")
                        .HasColumnType("text");

                    b.Property<string>("S2PrePenetration")
                        .HasColumnType("text");

                    b.Property<string>("S2PreThickness")
                        .HasColumnType("text");

                    b.Property<string>("S2RejLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2RejUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("TurretRpm")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrentBatches");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.Privilage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Alarms")
                        .HasColumnType("boolean");

                    b.Property<string>("PrivilegeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupPrivileges");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.PrivilageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Factor")
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("LoadCellCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("MaxVolt")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("MinVolt")
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("Offset")
                        .HasColumnType("numeric(18,8)");

                    b.HasKey("Id");

                    b.ToTable("LoadCellCalibrations");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AwcForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcLower")
                        .HasColumnType("real");

                    b.Property<float?>("AwcUpper")
                        .HasColumnType("real");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("FillDepthS1")
                        .HasColumnType("real");

                    b.Property<float?>("FillDepthS2")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS1")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxTurretRpm")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<float?>("RejLower")
                        .HasColumnType("real");

                    b.Property<float?>("RejUpper")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS2")
                        .HasColumnType("real");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<float?>("TabletHardness")
                        .HasColumnType("real");

                    b.Property<float?>("TabletThickness")
                        .HasColumnType("real");

                    b.Property<string>("ToolType")
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.RecipeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("AwcForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS1")
                        .HasColumnType("real");

                    b.Property<float?>("AwcForceSetPointS2")
                        .HasColumnType("real");

                    b.Property<float?>("AwcLower")
                        .HasColumnType("real");

                    b.Property<float?>("AwcUpper")
                        .HasColumnType("real");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<float?>("FillDepthS1")
                        .HasColumnType("real");

                    b.Property<float?>("FillDepthS2")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS1")
                        .HasColumnType("real");

                    b.Property<float?>("ForceFeederRatioS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainPenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("MainThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxEjectionForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxMainCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS1")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPreCompForceS2")
                        .HasColumnType("real");

                    b.Property<float?>("MaxTurretRpm")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PrePenetrationPositionS2")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS1")
                        .HasColumnType("real");

                    b.Property<float?>("PreThicknessPositionS2")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<string>("RecipeAlteredBy")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<float?>("RejLower")
                        .HasColumnType("real");

                    b.Property<float?>("RejUpper")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMaxS2")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS1")
                        .HasColumnType("real");

                    b.Property<float?>("RejectionForceLimitMinS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleIntervalS2")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS1")
                        .HasColumnType("real");

                    b.Property<float?>("SampleRevolutionQtyS2")
                        .HasColumnType("real");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<float?>("TabletHardness")
                        .HasColumnType("real");

                    b.Property<float?>("TabletThickness")
                        .HasColumnType("real");

                    b.Property<string>("ToolType")
                        .HasColumnType("text");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("RecipeHistroys");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultEjectLoadS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultEjectLoadS1Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultEjectLoadS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultEjectLoadS2Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultMainLoadS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultMainLoadS1Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultMainLoadS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultMainLoadS2Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultMainSrelS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageS1")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FeederSpeedS1")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValueS1")
                        .HasColumnType("double precision");

                    b.Property<double?>("TabletQtyS1")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ResultMainSrelS1Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultMainSrelS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageS2")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FeederSpeedS2")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValueS2")
                        .HasColumnType("double precision");

                    b.Property<double?>("TabletQtyS2")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ResultMainSrelS2Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultPreLoadS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SecuritySettings");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ResultPreLoadS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultPreLoadS2Bs");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.ServoCalibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Axis10Position")
                        .HasColumnType("double precision");

                    b.Property<double?>("Axis1Position")
                        .HasColumnType("double precision");

                    b.Property<double?>("Axis2Position")
                        .HasColumnType("double precision");

                    b.Property<double?>("Axis3Position")
                        .HasColumnType("double precision");

                    b.Property<double?>("Axis4Position")
                        .HasColumnType("double precision");

                    b.Property<double?>("Axis5Position")
                        .HasColumnType("double precision");

                    b.Property<string>("ServoCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ServoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("SetPosition")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SetSpeed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TorqueLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ServoCalibrations");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserLoginHistroy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ERemail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERlevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("UserStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserLoginHistroys");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangePw")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserManagements");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserManagementHistroy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ERdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserManagements");
                });

            modelBuilder.Entity("Compression_Force.Domain.Entities.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LoadCellCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LoadCellName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("LoadCellCode")
                        .IsUnique();

                    b.ToTable("LoadCells");
                });
#pragma warning restore 612, 618
        }
    }
}
