<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CompressionForce.Services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompressionForce.Data\CompressionForce.Data.csproj" />
    <ProjectReference Include="..\CompressionForce.Domain\CompressionForce.Domain.csproj" />
  </ItemGroup>

</Project>
